services:
  backend:
    build:
      context: ./backend
    container_name: socratic-backend
    environment:
      - EXERCISES_DIR=/app/exercises
      - OLLAMA_URL=http://ollama-service:11434
      - EXEC_MEMORY_LIMIT_MB=128
      - EXEC_TIMEOUT_SEC=90
    env_file:
      - .env
    networks:
      - ollama-net
      - frontend-net
    depends_on:
      - ollama-service

  frontend:
    build:
      context: ./frontend
    container_name: socratic-frontend
    networks:
      - frontend-net
    depends_on:
      - backend

  ollama-service:
    image: ollama/ollama:latest
    container_name: socratic-ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama-net

networks:
  frontend-net:
    driver: bridge
  ollama-net:
    driver: bridge

volumes:
  ollama_data: