services:
  backend:
    build:
      target: production
    ports:
      - "5000:5000"
    volumes:
      - ./exercises:/app/exercises

  frontend:
    build:
      target: production
    ports:
      - "8080:80"