# compose configuration override for production purposes.
services:
  backend:
    build:
      target: production
    restart: unless-stopped
      

  frontend:
    build:
      target: production
    ports:
      - "8080:80"
    restart: unless-stopped