services:
  web-app:
    command: npm run dev
    build: .
    container_name: socratic-tutor-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # mounts backend source
      - ./exercises:/app/exercises
      - ./frontend/dist:/app/public # shows the built frontend in public
      - /app/node_modules # preserves backend node_modules
    environment:
      - EXERCISES_DIR=/app/exercises
    networks:
      - llm-network
    depends_on:
      - ollama-service

  ollama-service:
    image: ollama/ollama:latest
    container_name: socratic-ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge

volumes:
  ollama_data: