# compose configuration override for production purposes.
services:
  backend:
    build:
      target: production
    ports:
      - "5000:5000"
      

  frontend:
    build:
      target: production
    ports:
      - "8080:80"