# base file for common docker compose configuration
# sets the backend and frontend services
services:
  backend:
    build:
      context: ./backend
    container_name: socratic-backend
    environment:
      - EXEC_MEMORY_LIMIT_MB=128 # child process max memory usage in megabytes
      - EXEC_TIMEOUT_SEC=90 # child process max run time in seconds
    env_file:
      - path: .env
        required: false
    networks:
      - frontend-net
    volumes:
      - ./exercises:/app/exercises

  frontend:
    build:
      context: ./frontend
    container_name: socratic-frontend
    networks:
      - frontend-net
    depends_on:
      - backend

networks:
  frontend-net:
    driver: bridge