import type { Completion } from "@codemirror/autocomplete";

/* This list is a simple yet effective workaround for CodeMirror's autocompletion.
This eliminates the need for an LSP server to autocomplete library functions. */
export const cCompletions: Completion[] = [

    // ─── Keywords ────────────────────────────────────────────────────────────────
    { label: "auto",           type: "keyword" },
    { label: "break",          type: "keyword" },
    { label: "case",           type: "keyword" },
    { label: "const",          type: "keyword" },
    { label: "continue",       type: "keyword" },
    { label: "default",        type: "keyword" },
    { label: "do",             type: "keyword" },
    { label: "else",           type: "keyword" },
    { label: "enum",           type: "keyword" },
    { label: "extern",         type: "keyword" },
    { label: "for",            type: "keyword" },
    { label: "goto",           type: "keyword" },
    { label: "if",             type: "keyword" },
    { label: "inline",         type: "keyword" },
    { label: "register",       type: "keyword" },
    { label: "restrict",       type: "keyword" },
    { label: "return",         type: "keyword" },
    { label: "sizeof",         type: "keyword" },
    { label: "static",         type: "keyword" },
    { label: "struct",         type: "keyword" },
    { label: "switch",         type: "keyword" },
    { label: "typedef",        type: "keyword" },
    { label: "union",          type: "keyword" },
    { label: "unsigned",       type: "keyword" },
    { label: "volatile",       type: "keyword" },
    { label: "while",          type: "keyword" },
    { label: "_Alignas",       type: "keyword" },
    { label: "_Alignof",       type: "keyword" },
    { label: "_Atomic",        type: "keyword" },
    { label: "_Generic",       type: "keyword" },
    { label: "_Noreturn",      type: "keyword" },
    { label: "_Static_assert", type: "keyword" },
    { label: "_Thread_local",  type: "keyword" },

    // ─── Primitives types ──────────────────────────────────────────────────────────
    { label: "int",            type: "type" },
    { label: "char",           type: "type" },
    { label: "float",          type: "type" },
    { label: "double",         type: "type" },
    { label: "void",           type: "type" },
    { label: "short",          type: "type" },
    { label: "long",           type: "type" },
    { label: "signed",         type: "type" },

    // ─── stdint.h types ───────────────────────────────────────────────────────────
    { label: "int8_t",         type: "type", detail: "<stdint.h>" },
    { label: "int16_t",        type: "type", detail: "<stdint.h>" },
    { label: "int32_t",        type: "type", detail: "<stdint.h>" },
    { label: "int64_t",        type: "type", detail: "<stdint.h>" },
    { label: "uint8_t",        type: "type", detail: "<stdint.h>" },
    { label: "uint16_t",       type: "type", detail: "<stdint.h>" },
    { label: "uint32_t",       type: "type", detail: "<stdint.h>" },
    { label: "uint64_t",       type: "type", detail: "<stdint.h>" },
    { label: "intptr_t",       type: "type", detail: "<stdint.h>" },
    { label: "uintptr_t",      type: "type", detail: "<stdint.h>" },
    { label: "intmax_t",       type: "type", detail: "<stdint.h>" },
    { label: "uintmax_t",      type: "type", detail: "<stdint.h>" },
    { label: "int_least8_t",   type: "type", detail: "<stdint.h>" },
    { label: "int_least16_t",  type: "type", detail: "<stdint.h>" },
    { label: "int_least32_t",  type: "type", detail: "<stdint.h>" },
    { label: "int_least64_t",  type: "type", detail: "<stdint.h>" },
    { label: "uint_least8_t",  type: "type", detail: "<stdint.h>" },
    { label: "uint_least16_t", type: "type", detail: "<stdint.h>" },
    { label: "uint_least32_t", type: "type", detail: "<stdint.h>" },
    { label: "uint_least64_t", type: "type", detail: "<stdint.h>" },

    // ─── stddef.h types ───────────────────────────────────────────────────────────
    { label: "size_t",         type: "type", detail: "<stddef.h>" },
    { label: "ptrdiff_t",      type: "type", detail: "<stddef.h>" },
    { label: "wchar_t",        type: "type", detail: "<stddef.h>" },
    { label: "NULL",           type: "constant", detail: "<stddef.h>", info: "Puntatore nullo" },
    { label: "offsetof",       type: "function", detail: "offsetof(type, member)", info: "Offset di un campo in una struct" },

    // ─── stdbool.h types ──────────────────────────────────────────────────────────
    { label: "bool",           type: "type",     detail: "<stdbool.h>" },
    { label: "true",           type: "constant", detail: "<stdbool.h>" },
    { label: "false",          type: "constant", detail: "<stdbool.h>" },

    // ─── Common macros ────────────────────────────────────────────────────────────
    { label: "EOF",            type: "constant", detail: "<stdio.h>",  info: "Fine del file (-1)" },
    { label: "BUFSIZ",         type: "constant", detail: "<stdio.h>" },
    { label: "FILENAME_MAX",   type: "constant", detail: "<stdio.h>" },
    { label: "FOPEN_MAX",      type: "constant", detail: "<stdio.h>" },
    { label: "EXIT_SUCCESS",   type: "constant", detail: "<stdlib.h>", info: "Valore di uscita: 0" },
    { label: "EXIT_FAILURE",   type: "constant", detail: "<stdlib.h>", info: "Valore di uscita: 1" },
    { label: "RAND_MAX",       type: "constant", detail: "<stdlib.h>" },
    { label: "INT_MAX",        type: "constant", detail: "<limits.h>" },
    { label: "INT_MIN",        type: "constant", detail: "<limits.h>" },
    { label: "UINT_MAX",       type: "constant", detail: "<limits.h>" },
    { label: "LONG_MAX",       type: "constant", detail: "<limits.h>" },
    { label: "LONG_MIN",       type: "constant", detail: "<limits.h>" },
    { label: "CHAR_MAX",       type: "constant", detail: "<limits.h>" },
    { label: "CHAR_MIN",       type: "constant", detail: "<limits.h>" },
    { label: "FLT_MAX",        type: "constant", detail: "<float.h>" },
    { label: "DBL_MAX",        type: "constant", detail: "<float.h>" },
    { label: "FLT_EPSILON",    type: "constant", detail: "<float.h>" },
    { label: "DBL_EPSILON",    type: "constant", detail: "<float.h>" },
    { label: "M_PI",           type: "constant", detail: "<math.h>",   info: "π ≈ 3.14159265358979" },
    { label: "M_E",            type: "constant", detail: "<math.h>",   info: "e ≈ 2.71828182845905" },
    { label: "M_SQRT2",        type: "constant", detail: "<math.h>" },
    { label: "M_LN2",          type: "constant", detail: "<math.h>" },
    { label: "HUGE_VAL",       type: "constant", detail: "<math.h>" },
    { label: "INFINITY",       type: "constant", detail: "<math.h>" },
    { label: "NAN",            type: "constant", detail: "<math.h>" },
    { label: "STDIN_FILENO",   type: "constant", detail: "<unistd.h>", info: "File descriptor stdin (0)" },
    { label: "STDOUT_FILENO",  type: "constant", detail: "<unistd.h>", info: "File descriptor stdout (1)" },
    { label: "STDERR_FILENO",  type: "constant", detail: "<unistd.h>", info: "File descriptor stderr (2)" },
    { label: "errno",          type: "variable", detail: "<errno.h>",  info: "Codice errore dell'ultima syscall" },
    { label: "ENOENT",         type: "constant", detail: "<errno.h>",  info: "No such file or directory" },
    { label: "EACCES",         type: "constant", detail: "<errno.h>",  info: "Permission denied" },
    { label: "ENOMEM",         type: "constant", detail: "<errno.h>",  info: "Out of memory" },
    { label: "EINVAL",         type: "constant", detail: "<errno.h>",  info: "Invalid argument" },
    { label: "EEXIST",         type: "constant", detail: "<errno.h>",  info: "File already exists" },
    { label: "ERANGE",         type: "constant", detail: "<errno.h>",  info: "Result out of range" },
    { label: "EOVERFLOW",      type: "constant", detail: "<errno.h>" },
    { label: "EAGAIN",         type: "constant", detail: "<errno.h>",  info: "Try again (risorsa temporaneamente non disponibile)" },
    { label: "EBADF",          type: "constant", detail: "<errno.h>",  info: "Bad file descriptor" },
    { label: "EPERM",          type: "constant", detail: "<errno.h>",  info: "Operation not permitted" },

    // ─── stdio.h ─────────────────────────────────────────────────────────────────
    { label: "printf",    type: "function", detail: "int printf(const char *format, ...)",                info: "Stampa testo formattato su stdout" },
    { label: "fprintf",   type: "function", detail: "int fprintf(FILE *stream, const char *format, ...)", info: "Stampa testo formattato su un file" },
    { label: "sprintf",   type: "function", detail: "int sprintf(char *str, const char *format, ...)",    info: "Scrive testo formattato in una stringa" },
    { label: "snprintf",  type: "function", detail: "int snprintf(char *str, size_t n, const char *format, ...)", info: "sprintf con limite di caratteri (sicuro)" },
    { label: "vprintf",   type: "function", detail: "int vprintf(const char *format, va_list arg)" },
    { label: "vfprintf",  type: "function", detail: "int vfprintf(FILE *stream, const char *format, va_list arg)" },
    { label: "vsprintf",  type: "function", detail: "int vsprintf(char *str, const char *format, va_list arg)" },
    { label: "vsnprintf", type: "function", detail: "int vsnprintf(char *str, size_t n, const char *format, va_list arg)" },
    { label: "scanf",     type: "function", detail: "int scanf(const char *format, ...)",                 info: "Legge input formattato da stdin" },
    { label: "fscanf",    type: "function", detail: "int fscanf(FILE *stream, const char *format, ...)" },
    { label: "sscanf",    type: "function", detail: "int sscanf(const char *str, const char *format, ...)" },
    { label: "getchar",   type: "function", detail: "int getchar(void)",                                  info: "Legge un carattere da stdin" },
    { label: "putchar",   type: "function", detail: "int putchar(int c)",                                 info: "Scrive un carattere su stdout" },
    { label: "gets",      type: "function", detail: "char *gets(char *str)",                              info: "⚠ Deprecata: usa fgets" },
    { label: "puts",      type: "function", detail: "int puts(const char *str)",                          info: "Scrive una stringa su stdout con newline" },
    { label: "fopen",     type: "function", detail: "FILE *fopen(const char *filename, const char *mode)", info: "Apre un file. Mode: r, w, a, r+, w+, a+" },
    { label: "fclose",    type: "function", detail: "int fclose(FILE *stream)" },
    { label: "fread",     type: "function", detail: "size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream)" },
    { label: "fwrite",    type: "function", detail: "size_t fwrite(const void *ptr, size_t size, size_t nmemb, FILE *stream)" },
    { label: "fgets",     type: "function", detail: "char *fgets(char *str, int n, FILE *stream)",        info: "Legge una riga da un file (sicuro)" },
    { label: "fputs",     type: "function", detail: "int fputs(const char *str, FILE *stream)" },
    { label: "fgetc",     type: "function", detail: "int fgetc(FILE *stream)" },
    { label: "fputc",     type: "function", detail: "int fputc(int c, FILE *stream)" },
    { label: "feof",      type: "function", detail: "int feof(FILE *stream)",                             info: "Controlla se la fine del file è stata raggiunta" },
    { label: "ferror",    type: "function", detail: "int ferror(FILE *stream)" },
    { label: "clearerr",  type: "function", detail: "void clearerr(FILE *stream)" },
    { label: "fseek",     type: "function", detail: "int fseek(FILE *stream, long offset, int whence)",   info: "Sposta il cursore del file" },
    { label: "ftell",     type: "function", detail: "long ftell(FILE *stream)",                           info: "Restituisce la posizione corrente del cursore" },
    { label: "rewind",    type: "function", detail: "void rewind(FILE *stream)" },
    { label: "fflush",    type: "function", detail: "int fflush(FILE *stream)" },
    { label: "remove",    type: "function", detail: "int remove(const char *filename)" },
    { label: "rename",    type: "function", detail: "int rename(const char *oldname, const char *newname)" },
    { label: "tmpfile",   type: "function", detail: "FILE *tmpfile(void)" },
    { label: "tmpnam",    type: "function", detail: "char *tmpnam(char *str)" },
    { label: "perror",    type: "function", detail: "void perror(const char *str)",                       info: "Stampa il messaggio di errore corrente su stderr" },
    { label: "stdin",     type: "variable", detail: "FILE *",                                             info: "Stream di input standard" },
    { label: "stdout",    type: "variable", detail: "FILE *",                                             info: "Stream di output standard" },
    { label: "stderr",    type: "variable", detail: "FILE *",                                             info: "Stream di errore standard" },
    { label: "SEEK_SET",  type: "constant", detail: "<stdio.h>",                                          info: "Inizio file" },
    { label: "SEEK_CUR",  type: "constant", detail: "<stdio.h>",                                          info: "Posizione corrente" },
    { label: "SEEK_END",  type: "constant", detail: "<stdio.h>",                                          info: "Fine file" },
    { label: "FILE",      type: "type",     detail: "<stdio.h>" },

    // ─── stdlib.h ────────────────────────────────────────────────────────────────
    { label: "malloc",      type: "function", detail: "void *malloc(size_t size)",                          info: "Alloca memoria non inizializzata" },
    { label: "calloc",      type: "function", detail: "void *calloc(size_t nmemb, size_t size)",            info: "Alloca memoria inizializzata a zero" },
    { label: "realloc",     type: "function", detail: "void *realloc(void *ptr, size_t size)",              info: "Ridimensiona un blocco di memoria" },
    { label: "free",        type: "function", detail: "void free(void *ptr)",                               info: "Dealloca memoria allocata con malloc/calloc/realloc" },
    { label: "exit",        type: "function", detail: "void exit(int status)" },
    { label: "abort",       type: "function", detail: "void abort(void)",                                   info: "Termina il programma in modo anormale" },
    { label: "atexit",      type: "function", detail: "int atexit(void (*func)(void))",                     info: "Registra una funzione da chiamare all'uscita" },
    { label: "abs",         type: "function", detail: "int abs(int x)" },
    { label: "labs",        type: "function", detail: "long abs(long x)" },
    { label: "llabs",       type: "function", detail: "long long llabs(long long x)" },
    { label: "div",         type: "function", detail: "div_t div(int numer, int denom)" },
    { label: "ldiv",        type: "function", detail: "ldiv_t ldiv(long numer, long denom)" },
    { label: "rand",        type: "function", detail: "int rand(void)",                                     info: "Genera un numero pseudocasuale [0, RAND_MAX]" },
    { label: "srand",       type: "function", detail: "void srand(unsigned int seed)",                      info: "Inizializza il generatore di numeri casuali" },
    { label: "atoi",        type: "function", detail: "int atoi(const char *str)",                          info: "Converte stringa in int" },
    { label: "atol",        type: "function", detail: "long atol(const char *str)" },
    { label: "atoll",       type: "function", detail: "long long atoll(const char *str)" },
    { label: "atof",        type: "function", detail: "double atof(const char *str)",                       info: "Converte stringa in double" },
    { label: "strtol",      type: "function", detail: "long strtol(const char *str, char **endptr, int base)", info: "Converte stringa in long con base e rilevamento errori" },
    { label: "strtoul",     type: "function", detail: "unsigned long strtoul(const char *str, char **endptr, int base)" },
    { label: "strtoll",     type: "function", detail: "long long strtoll(const char *str, char **endptr, int base)" },
    { label: "strtoull",    type: "function", detail: "unsigned long long strtoull(const char *str, char **endptr, int base)" },
    { label: "strtod",      type: "function", detail: "double strtod(const char *str, char **endptr)" },
    { label: "strtof",      type: "function", detail: "float strtof(const char *str, char **endptr)" },
    { label: "strtold",     type: "function", detail: "long double strtold(const char *str, char **endptr)" },
    { label: "qsort",       type: "function", detail: "void qsort(void *base, size_t nmemb, size_t size, int (*compar)(const void*, const void*))", info: "Ordina un array" },
    { label: "bsearch",     type: "function", detail: "void *bsearch(const void *key, const void *base, size_t nmemb, size_t size, int (*compar)(const void*, const void*))", info: "Ricerca binaria in un array ordinato" },
    { label: "system",      type: "function", detail: "int system(const char *command)",                    info: "Esegue un comando shell" },
    { label: "getenv",      type: "function", detail: "char *getenv(const char *name)",                     info: "Ottiene una variabile d'ambiente" },
    { label: "setenv",      type: "function", detail: "int setenv(const char *name, const char *value, int overwrite)" },
    { label: "unsetenv",    type: "function", detail: "int unsetenv(const char *name)" },

    // ─── string.h ────────────────────────────────────────────────────────────────
    { label: "strlen",   type: "function", detail: "size_t strlen(const char *str)",                          info: "Lunghezza di una stringa (escluso \\0)" },
    { label: "strcpy",   type: "function", detail: "char *strcpy(char *dest, const char *src)",               info: "Copia una stringa. ⚠ Non verifica i bounds" },
    { label: "strncpy",  type: "function", detail: "char *strncpy(char *dest, const char *src, size_t n)",    info: "Copia al più n caratteri" },
    { label: "strcat",   type: "function", detail: "char *strcat(char *dest, const char *src)" },
    { label: "strncat",  type: "function", detail: "char *strncat(char *dest, const char *src, size_t n)" },
    { label: "strcmp",   type: "function", detail: "int strcmp(const char *str1, const char *str2)",          info: "Confronta due stringhe. Ritorna 0 se uguali" },
    { label: "strncmp",  type: "function", detail: "int strncmp(const char *str1, const char *str2, size_t n)" },
    { label: "strcasecmp",  type: "function", detail: "int strcasecmp(const char *str1, const char *str2)",   info: "Confronto case-insensitive (POSIX)" },
    { label: "strncasecmp", type: "function", detail: "int strncasecmp(const char *str1, const char *str2, size_t n)" },
    { label: "strchr",   type: "function", detail: "char *strchr(const char *str, int c)",                    info: "Cerca la prima occorrenza di c nella stringa" },
    { label: "strrchr",  type: "function", detail: "char *strrchr(const char *str, int c)",                   info: "Cerca l'ultima occorrenza di c nella stringa" },
    { label: "strstr",   type: "function", detail: "char *strstr(const char *haystack, const char *needle)",  info: "Cerca una sottostringa" },
    { label: "strtok",   type: "function", detail: "char *strtok(char *str, const char *delim)",              info: "Tokenizza una stringa (modifica l'originale)" },
    { label: "strtok_r", type: "function", detail: "char *strtok_r(char *str, const char *delim, char **saveptr)", info: "Thread-safe version of strtok" },
    { label: "strspn",   type: "function", detail: "size_t strspn(const char *str, const char *accept)" },
    { label: "strcspn",  type: "function", detail: "size_t strcspn(const char *str, const char *reject)" },
    { label: "strpbrk",  type: "function", detail: "char *strpbrk(const char *str, const char *accept)" },
    { label: "strerror", type: "function", detail: "char *strerror(int errnum)",                              info: "Restituisce il messaggio di errore per errnum" },
    { label: "strdup",   type: "function", detail: "char *strdup(const char *str)",                           info: "Duplica una stringa (alloca con malloc)" },
    { label: "strndup",  type: "function", detail: "char *strndup(const char *str, size_t n)" },
    { label: "memset",   type: "function", detail: "void *memset(void *ptr, int c, size_t n)",                info: "Riempie un blocco di memoria con un valore" },
    { label: "memcpy",   type: "function", detail: "void *memcpy(void *dest, const void *src, size_t n)",     info: "Copia un blocco di memoria (no overlap)" },
    { label: "memmove",  type: "function", detail: "void *memmove(void *dest, const void *src, size_t n)",    info: "Copia un blocco di memoria (gestisce overlap)" },
    { label: "memcmp",   type: "function", detail: "int memcmp(const void *ptr1, const void *ptr2, size_t n)" },
    { label: "memchr",   type: "function", detail: "void *memchr(const void *ptr, int value, size_t n)" },

    // ─── math.h ──────────────────────────────────────────────────────────────────
    { label: "sqrt",   type: "function", detail: "double sqrt(double x)",            info: "Radice quadrata" },
    { label: "cbrt",   type: "function", detail: "double cbrt(double x)",            info: "Radice cubica" },
    { label: "pow",    type: "function", detail: "double pow(double x, double y)",   info: "x elevato a y" },
    { label: "exp",    type: "function", detail: "double exp(double x)",             info: "e^x" },
    { label: "exp2",   type: "function", detail: "double exp2(double x)",            info: "2^x" },
    { label: "log",    type: "function", detail: "double log(double x)",             info: "Logaritmo naturale" },
    { label: "log2",   type: "function", detail: "double log2(double x)",            info: "Logaritmo base 2" },
    { label: "log10",  type: "function", detail: "double log10(double x)",           info: "Logaritmo base 10" },
    { label: "fabs",   type: "function", detail: "double fabs(double x)",            info: "Valore assoluto (double)" },
    { label: "fabsf",  type: "function", detail: "float fabsf(float x)" },
    { label: "ceil",   type: "function", detail: "double ceil(double x)",            info: "Arrotonda verso l'alto" },
    { label: "floor",  type: "function", detail: "double floor(double x)",           info: "Arrotonda verso il basso" },
    { label: "round",  type: "function", detail: "double round(double x)",           info: "Arrotonda al più vicino" },
    { label: "trunc",  type: "function", detail: "double trunc(double x)",           info: "Tronca verso zero" },
    { label: "fmod",   type: "function", detail: "double fmod(double x, double y)",  info: "Resto della divisione tra double" },
    { label: "fmin",   type: "function", detail: "double fmin(double x, double y)" },
    { label: "fmax",   type: "function", detail: "double fmax(double x, double y)" },
    { label: "sin",    type: "function", detail: "double sin(double x)" },
    { label: "cos",    type: "function", detail: "double cos(double x)" },
    { label: "tan",    type: "function", detail: "double tan(double x)" },
    { label: "asin",   type: "function", detail: "double asin(double x)" },
    { label: "acos",   type: "function", detail: "double acos(double x)" },
    { label: "atan",   type: "function", detail: "double atan(double x)" },
    { label: "atan2",  type: "function", detail: "double atan2(double y, double x)", info: "Angolo dell'arco tangente di y/x nel quadrante corretto" },
    { label: "sinh",   type: "function", detail: "double sinh(double x)" },
    { label: "cosh",   type: "function", detail: "double cosh(double x)" },
    { label: "tanh",   type: "function", detail: "double tanh(double x)" },
    { label: "hypot",  type: "function", detail: "double hypot(double x, double y)", info: "sqrt(x² + y²)" },
    { label: "isinf",  type: "function", detail: "int isinf(double x)" },
    { label: "isnan",  type: "function", detail: "int isnan(double x)" },
    { label: "isfinite", type: "function", detail: "int isfinite(double x)" },
    { label: "fpclassify", type: "function", detail: "int fpclassify(double x)" },

    // ─── ctype.h ─────────────────────────────────────────────────────────────────
    { label: "isalpha",  type: "function", detail: "int isalpha(int c)",  info: "Vero se c è una lettera" },
    { label: "isdigit",  type: "function", detail: "int isdigit(int c)",  info: "Vero se c è una cifra 0-9" },
    { label: "isalnum",  type: "function", detail: "int isalnum(int c)",  info: "Vero se c è lettera o cifra" },
    { label: "isspace",  type: "function", detail: "int isspace(int c)",  info: "Vero se c è spazio, tab, newline..." },
    { label: "isupper",  type: "function", detail: "int isupper(int c)" },
    { label: "islower",  type: "function", detail: "int islower(int c)" },
    { label: "isprint",  type: "function", detail: "int isprint(int c)",  info: "Vero se c è un carattere stampabile" },
    { label: "ispunct",  type: "function", detail: "int ispunct(int c)" },
    { label: "iscntrl",  type: "function", detail: "int iscntrl(int c)" },
    { label: "isxdigit", type: "function", detail: "int isxdigit(int c)", info: "Vero se c è una cifra esadecimale" },
    { label: "toupper",  type: "function", detail: "int toupper(int c)",  info: "Converte in maiuscolo" },
    { label: "tolower",  type: "function", detail: "int tolower(int c)",  info: "Converte in minuscolo" },

    // ─── time.h ──────────────────────────────────────────────────────────────────
    { label: "time",       type: "function", detail: "time_t time(time_t *timer)",                   info: "Restituisce il tempo corrente in secondi (epoch)" },
    { label: "clock",      type: "function", detail: "clock_t clock(void)",                          info: "Tempo CPU usato dal processo" },
    { label: "difftime",   type: "function", detail: "double difftime(time_t time1, time_t time0)",  info: "Differenza in secondi tra due time_t" },
    { label: "mktime",     type: "function", detail: "time_t mktime(struct tm *timeptr)" },
    { label: "localtime",  type: "function", detail: "struct tm *localtime(const time_t *timer)" },
    { label: "gmtime",     type: "function", detail: "struct tm *gmtime(const time_t *timer)" },
    { label: "asctime",    type: "function", detail: "char *asctime(const struct tm *timeptr)" },
    { label: "ctime",      type: "function", detail: "char *ctime(const time_t *timer)" },
    { label: "strftime",   type: "function", detail: "size_t strftime(char *str, size_t maxsize, const char *format, const struct tm *timeptr)", info: "Formatta una data/ora come stringa" },
    { label: "time_t",     type: "type",     detail: "<time.h>" },
    { label: "clock_t",    type: "type",     detail: "<time.h>" },
    { label: "CLOCKS_PER_SEC", type: "constant", detail: "<time.h>" },

    // ─── assert.h ────────────────────────────────────────────────────────────────
    { label: "assert", type: "function", detail: "void assert(int expression)", info: "Termina il programma se l'espressione è falsa (in debug)" },

    // ─── stdarg.h ────────────────────────────────────────────────────────────────
    { label: "va_list",  type: "type",     detail: "<stdarg.h>",                                info: "Tipo per argomenti variabili" },
    { label: "va_start", type: "function", detail: "void va_start(va_list ap, last)",           info: "Inizializza la lista di argomenti variabili" },
    { label: "va_arg",   type: "function", detail: "type va_arg(va_list ap, type)",             info: "Legge il prossimo argomento variabile" },
    { label: "va_end",   type: "function", detail: "void va_end(va_list ap)" },
    { label: "va_copy",  type: "function", detail: "void va_copy(va_list dest, va_list src)" },

    // ─── signal.h ────────────────────────────────────────────────────────────────
    { label: "signal",  type: "function", detail: "void (*signal(int signum, void (*handler)(int)))(int)" },
    { label: "raise",   type: "function", detail: "int raise(int sig)" },
    { label: "SIGINT",  type: "constant", detail: "<signal.h>", info: "Interrupt (Ctrl+C)" },
    { label: "SIGTERM", type: "constant", detail: "<signal.h>", info: "Terminazione" },
    { label: "SIGSEGV", type: "constant", detail: "<signal.h>", info: "Segmentation fault" },
    { label: "SIGFPE",  type: "constant", detail: "<signal.h>", info: "Floating-point exception" },
    { label: "SIGABRT", type: "constant", detail: "<signal.h>", info: "Abort" },
    { label: "SIGILL",  type: "constant", detail: "<signal.h>", info: "Illegal instruction" },
    { label: "SIG_DFL", type: "constant", detail: "<signal.h>", info: "Handler di default" },
    { label: "SIG_IGN", type: "constant", detail: "<signal.h>", info: "Ignora il segnale" },

    // ─── setjmp.h ────────────────────────────────────────────────────────────────
    { label: "setjmp",  type: "function", detail: "int setjmp(jmp_buf env)",              info: "Salva il contesto di esecuzione" },
    { label: "longjmp", type: "function", detail: "void longjmp(jmp_buf env, int value)", info: "Ripristina un contesto salvato con setjmp" },
    { label: "jmp_buf", type: "type",     detail: "<setjmp.h>" },

    // ─── unistd.h (POSIX) ────────────────────────────────────────────────────────
    { label: "read",    type: "function", detail: "ssize_t read(int fd, void *buf, size_t count)" },
    { label: "write",   type: "function", detail: "ssize_t write(int fd, const void *buf, size_t count)" },
    { label: "close",   type: "function", detail: "int close(int fd)" },
    { label: "open",    type: "function", detail: "int open(const char *pathname, int flags, ...)",     info: "Apre/crea un file (POSIX). Flags: O_RDONLY, O_WRONLY, O_RDWR, O_CREAT..." },
    { label: "lseek",   type: "function", detail: "off_t lseek(int fd, off_t offset, int whence)" },
    { label: "dup",     type: "function", detail: "int dup(int oldfd)" },
    { label: "dup2",    type: "function", detail: "int dup2(int oldfd, int newfd)" },
    { label: "pipe",    type: "function", detail: "int pipe(int pipefd[2])" },
    { label: "fork",    type: "function", detail: "pid_t fork(void)",                                   info: "Crea un processo figlio (clone del padre)" },
    { label: "exec",    type: "function", detail: "int exec*(const char *path, ...)",                   info: "Sostituisce l'immagine del processo" },
    { label: "execl",   type: "function", detail: "int execl(const char *path, const char *arg, ...)" },
    { label: "execv",   type: "function", detail: "int execv(const char *path, char *const argv[])" },
    { label: "execvp",  type: "function", detail: "int execvp(const char *file, char *const argv[])" },
    { label: "getpid",  type: "function", detail: "pid_t getpid(void)",  info: "PID del processo corrente" },
    { label: "getppid", type: "function", detail: "pid_t getppid(void)", info: "PID del processo padre" },
    { label: "sleep",   type: "function", detail: "unsigned int sleep(unsigned int seconds)" },
    { label: "usleep",  type: "function", detail: "int usleep(useconds_t usec)",                        info: "Pausa in microsecondi" },
    { label: "getcwd",  type: "function", detail: "char *getcwd(char *buf, size_t size)" },
    { label: "chdir",   type: "function", detail: "int chdir(const char *path)" },
    { label: "access",  type: "function", detail: "int access(const char *pathname, int mode)" },
    { label: "unlink",  type: "function", detail: "int unlink(const char *pathname)",                   info: "Elimina un file" },
    { label: "pid_t",   type: "type",     detail: "<unistd.h>" },
    { label: "ssize_t", type: "type",     detail: "<unistd.h>" },
    { label: "off_t",   type: "type",     detail: "<unistd.h>" },
    { label: "O_RDONLY",type: "constant", detail: "<fcntl.h>" },
    { label: "O_WRONLY",type: "constant", detail: "<fcntl.h>" },
    { label: "O_RDWR",  type: "constant", detail: "<fcntl.h>" },
    { label: "O_CREAT", type: "constant", detail: "<fcntl.h>" },
    { label: "O_TRUNC", type: "constant", detail: "<fcntl.h>" },
    { label: "O_APPEND",type: "constant", detail: "<fcntl.h>" },
    { label: "O_NONBLOCK", type: "constant", detail: "<fcntl.h>" },

    // ─── sys/wait.h (POSIX) ──────────────────────────────────────────────────────
    { label: "wait",    type: "function", detail: "pid_t wait(int *status)" },
    { label: "waitpid", type: "function", detail: "pid_t waitpid(pid_t pid, int *status, int options)" },
    { label: "WIFEXITED",    type: "function", detail: "int WIFEXITED(int status)" },
    { label: "WEXITSTATUS",  type: "function", detail: "int WEXITSTATUS(int status)" },
    { label: "WIFSIGNALED",  type: "function", detail: "int WIFSIGNALED(int status)" },
    { label: "WTERMSIG",     type: "function", detail: "int WTERMSIG(int status)" },
    { label: "WNOHANG",      type: "constant", detail: "<sys/wait.h>" },

    // ─── sys/socket.h (POSIX networking) ─────────────────────────────────────────
    { label: "socket",   type: "function", detail: "int socket(int domain, int type, int protocol)" },
    { label: "bind",     type: "function", detail: "int bind(int sockfd, const struct sockaddr *addr, socklen_t addrlen)" },
    { label: "listen",   type: "function", detail: "int listen(int sockfd, int backlog)" },
    { label: "accept",   type: "function", detail: "int accept(int sockfd, struct sockaddr *addr, socklen_t *addrlen)" },
    { label: "connect",  type: "function", detail: "int connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen)" },
    { label: "send",     type: "function", detail: "ssize_t send(int sockfd, const void *buf, size_t len, int flags)" },
    { label: "recv",     type: "function", detail: "ssize_t recv(int sockfd, void *buf, size_t len, int flags)" },
    { label: "sendto",   type: "function", detail: "ssize_t sendto(int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *dest_addr, socklen_t addrlen)" },
    { label: "recvfrom", type: "function", detail: "ssize_t recvfrom(int sockfd, void *buf, size_t len, int flags, struct sockaddr *src_addr, socklen_t *addrlen)" },
    { label: "setsockopt", type: "function", detail: "int setsockopt(int sockfd, int level, int optname, const void *optval, socklen_t optlen)" },
    { label: "getsockopt", type: "function", detail: "int getsockopt(int sockfd, int level, int optname, void *optval, socklen_t *optlen)" },
    { label: "shutdown", type: "function", detail: "int shutdown(int sockfd, int how)" },
    { label: "htons",    type: "function", detail: "uint16_t htons(uint16_t hostshort)",  info: "Host to Network Short (byte order)" },
    { label: "htonl",    type: "function", detail: "uint32_t htonl(uint32_t hostlong)" },
    { label: "ntohs",    type: "function", detail: "uint16_t ntohs(uint16_t netshort)" },
    { label: "ntohl",    type: "function", detail: "uint32_t ntohl(uint32_t netlong)" },
    { label: "inet_pton",type: "function", detail: "int inet_pton(int af, const char *src, void *dst)", info: "Converte indirizzo IP stringa → binario" },
    { label: "inet_ntop",type: "function", detail: "const char *inet_ntop(int af, const void *src, char *dst, socklen_t size)" },
    { label: "AF_INET",  type: "constant", detail: "<sys/socket.h>", info: "IPv4" },
    { label: "AF_INET6", type: "constant", detail: "<sys/socket.h>", info: "IPv6" },
    { label: "AF_UNIX",  type: "constant", detail: "<sys/socket.h>", info: "Unix domain socket" },
    { label: "SOCK_STREAM",   type: "constant", detail: "<sys/socket.h>", info: "TCP" },
    { label: "SOCK_DGRAM",    type: "constant", detail: "<sys/socket.h>", info: "UDP" },
    { label: "SOCK_RAW",      type: "constant", detail: "<sys/socket.h>" },
    { label: "SOL_SOCKET",    type: "constant", detail: "<sys/socket.h>" },
    { label: "SO_REUSEADDR",  type: "constant", detail: "<sys/socket.h>" },
    { label: "SO_KEEPALIVE",  type: "constant", detail: "<sys/socket.h>" },
    { label: "IPPROTO_TCP",   type: "constant", detail: "<netinet/in.h>" },
    { label: "IPPROTO_UDP",   type: "constant", detail: "<netinet/in.h>" },
    { label: "INADDR_ANY",    type: "constant", detail: "<netinet/in.h>", info: "Bind su tutti gli indirizzi (0.0.0.0)" },
    { label: "INADDR_LOOPBACK", type: "constant", detail: "<netinet/in.h>", info: "127.0.0.1" },

    // ─── pthread.h ───────────────────────────────────────────────────────────────
    { label: "pthread_create",    type: "function", detail: "int pthread_create(pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(void*), void *arg)" },
    { label: "pthread_join",      type: "function", detail: "int pthread_join(pthread_t thread, void **retval)" },
    { label: "pthread_detach",    type: "function", detail: "int pthread_detach(pthread_t thread)" },
    { label: "pthread_exit",      type: "function", detail: "void pthread_exit(void *retval)" },
    { label: "pthread_self",      type: "function", detail: "pthread_t pthread_self(void)" },
    { label: "pthread_cancel",    type: "function", detail: "int pthread_cancel(pthread_t thread)" },
    { label: "pthread_mutex_init",    type: "function", detail: "int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)" },
    { label: "pthread_mutex_destroy", type: "function", detail: "int pthread_mutex_destroy(pthread_mutex_t *mutex)" },
    { label: "pthread_mutex_lock",    type: "function", detail: "int pthread_mutex_lock(pthread_mutex_t *mutex)" },
    { label: "pthread_mutex_unlock",  type: "function", detail: "int pthread_mutex_unlock(pthread_mutex_t *mutex)" },
    { label: "pthread_mutex_trylock", type: "function", detail: "int pthread_mutex_trylock(pthread_mutex_t *mutex)" },
    { label: "pthread_cond_init",     type: "function", detail: "int pthread_cond_init(pthread_cond_t *cond, const pthread_condattr_t *attr)" },
    { label: "pthread_cond_destroy",  type: "function", detail: "int pthread_cond_destroy(pthread_cond_t *cond)" },
    { label: "pthread_cond_wait",     type: "function", detail: "int pthread_cond_wait(pthread_cond_t *cond, pthread_mutex_t *mutex)" },
    { label: "pthread_cond_signal",   type: "function", detail: "int pthread_cond_signal(pthread_cond_t *cond)" },
    { label: "pthread_cond_broadcast",type: "function", detail: "int pthread_cond_broadcast(pthread_cond_t *cond)" },
    { label: "pthread_rwlock_rdlock", type: "function", detail: "int pthread_rwlock_rdlock(pthread_rwlock_t *rwlock)" },
    { label: "pthread_rwlock_wrlock", type: "function", detail: "int pthread_rwlock_wrlock(pthread_rwlock_t *rwlock)" },
    { label: "pthread_rwlock_unlock", type: "function", detail: "int pthread_rwlock_unlock(pthread_rwlock_t *rwlock)" },
    { label: "pthread_t",             type: "type",     detail: "<pthread.h>" },
    { label: "pthread_mutex_t",       type: "type",     detail: "<pthread.h>" },
    { label: "pthread_cond_t",        type: "type",     detail: "<pthread.h>" },
    { label: "pthread_rwlock_t",      type: "type",     detail: "<pthread.h>" },
    { label: "PTHREAD_MUTEX_INITIALIZER", type: "constant", detail: "<pthread.h>" },
    { label: "PTHREAD_COND_INITIALIZER",  type: "constant", detail: "<pthread.h>" },

    // ─── sys/stat.h / dirent.h ───────────────────────────────────────────────────
    { label: "stat",    type: "function", detail: "int stat(const char *pathname, struct stat *statbuf)" },
    { label: "fstat",   type: "function", detail: "int fstat(int fd, struct stat *statbuf)" },
    { label: "lstat",   type: "function", detail: "int lstat(const char *pathname, struct stat *statbuf)" },
    { label: "mkdir",   type: "function", detail: "int mkdir(const char *pathname, mode_t mode)" },
    { label: "rmdir",   type: "function", detail: "int rmdir(const char *pathname)" },
    { label: "chmod",   type: "function", detail: "int chmod(const char *pathname, mode_t mode)" },
    { label: "opendir", type: "function", detail: "DIR *opendir(const char *name)" },
    { label: "readdir", type: "function", detail: "struct dirent *readdir(DIR *dirp)" },
    { label: "closedir",type: "function", detail: "int closedir(DIR *dirp)" },
    { label: "S_IRWXU", type: "constant", detail: "<sys/stat.h>", info: "rwx per il proprietario (0700)" },
    { label: "S_IRUSR", type: "constant", detail: "<sys/stat.h>" },
    { label: "S_IWUSR", type: "constant", detail: "<sys/stat.h>" },
    { label: "S_IXUSR", type: "constant", detail: "<sys/stat.h>" },
    { label: "S_ISREG", type: "function", detail: "int S_ISREG(mode_t m)",  info: "Vero se è un file regolare" },
    { label: "S_ISDIR", type: "function", detail: "int S_ISDIR(mode_t m)",  info: "Vero se è una directory" },
    { label: "S_ISLNK", type: "function", detail: "int S_ISLNK(mode_t m)",  info: "Vero se è un symlink" },

    // ─── preprocessor ───────────────────────────────────────────────────────────
    { label: "#include",       type: "keyword" },
    { label: "#define",        type: "keyword" },
    { label: "#undef",         type: "keyword" },
    { label: "#ifdef",         type: "keyword" },
    { label: "#ifndef",        type: "keyword" },
    { label: "#if",            type: "keyword" },
    { label: "#elif",          type: "keyword" },
    { label: "#else",          type: "keyword" },
    { label: "#endif",         type: "keyword" },
    { label: "#pragma",        type: "keyword" },
    { label: "#pragma once",   type: "keyword", info: "Include guard moderno (non standard ma universale)" },
    { label: "__FILE__",       type: "constant", info: "Percorso del file sorgente corrente" },
    { label: "__LINE__",       type: "constant", info: "Numero di riga corrente" },
    { label: "__func__",       type: "constant", info: "Nome della funzione corrente" },
    { label: "__DATE__",       type: "constant" },
    { label: "__TIME__",       type: "constant" },
    { label: "__STDC_VERSION__", type: "constant" },
];

import { completeFromList, completeAnyWord } from "@codemirror/autocomplete";
import type { CompletionContext, CompletionResult } from "@codemirror/autocomplete";

const cStaticSource = completeFromList(cCompletions);

/* Completition source for CodeMirror. To use in the autocompletition override.
Merges C static completitions with completeAnyWord to autocomplete both standard
library functions, types, macros and user defined variables, types, etc... */
export async function cCompletionSource(context: CompletionContext): Promise<CompletionResult | null> {
    const staticResult = await cStaticSource(context);
    const wordResult = await completeAnyWord(context);

    // can't autocomplete
    if (!staticResult && !wordResult) {
        return null;
    }

    const staticOptions = staticResult?.options ?? [];
    const wordOptions = wordResult?.options ?? [];
    const allOptions = [...staticOptions, ...wordOptions];
    
    // merges static and user defined words
    const uniqueOptions = Array.from(new Map(allOptions.map(o => [o.label, o])).values());

    return {
        from: staticResult?.from ?? wordResult?.from ?? context.pos,
        options: uniqueOptions,
        validFor: /^\w*$/
    };
}