import { ChatMessage } from "../types";

const API_URL = "/api/ai/chat";

/**
 * sends the context to the LLM and generates the token
 * received in response.
 * @param messages : the chat context
 * @param exerciseName : the name of the exercise used for context 
 * @returns the tokens generated by the stream
 */
export const streamChat = async function* (
    messages: ChatMessage[],
    exerciseName: string
): AsyncGenerator<string> {
    const response = await fetch(API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages, exerciseName })
    });

    if (!response.ok) throw new Error(`HTTP error: ${response.status}`);

    const reader = response.body!.getReader();
    const decoder = new TextDecoder();

    while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const lines = decoder.decode(value).split("\n").filter(Boolean);

        for (const line of lines) {
            if (!line.startsWith("data: ")) {
                continue;
            }
            const data = JSON.parse(line.slice(6));
            if (data.done) {
                return;
            }
            if (data.token) {
                yield data.token;
            }
        }
    }
};